import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, ErrorBanner, PageHeader, Skeleton } from '../components/UI'
import { api, errorMessage, type AnalysisResponse, type ImplementResponse } from '../lib/api'

export function ObservationPage() {
  const { id = '' } = useParams()
  const [analysis, setAnalysis] = useState<AnalysisResponse | null>(null)
  const [plan, setPlan] = useState<ImplementResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [implementing, setImplementing] = useState('')
  const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setAnalysis(await api.getAnalysis(id)) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load])
  async function implement(solutionId: string) { setImplementing(solutionId); setError(''); try { setPlan(await api.implementSolution(id, solutionId)) } catch (err) { setError(errorMessage(err)) } finally { setImplementing('') } }
  return <div className="page"><PageHeader eyebrow="Observation analysis" title="Connected intelligence" description="SynapseOS is tracing this signal across organizational memory and proven solutions." action={<Link className="secondary-button" to="/observations/new">New observation</Link>} />{error && <ErrorBanner message={error} onRetry={!analysis ? load : undefined} />}{loading ? <AnalysisSkeleton /> : analysis ? <><section className="analysis-hero card"><div className="confidence-ring" style={{ '--score': `${analysis.overall_confidence_score * 360}deg` } as React.CSSProperties}><div><strong>{Math.round(analysis.overall_confidence_score * 100)}%</strong><span>confidence</span></div></div><div><p className="eyebrow">Cross-functional pattern found</p><h2>Related onboarding signals and prior solutions are ready</h2><p>Five intelligence agents completed the analysis and found reusable organizational knowledge.</p></div></section><section className="analysis-grid"><article className="card"><SectionTitle title="Agent trace" count={analysis.agent_trace.length} /> <div className="trace-list">{analysis.agent_trace.map((agent, index) => <div className="trace-item" key={agent.agent_name} style={{ animationDelay: `${index * 80}ms` }}><span className="trace-check">✓</span><div><strong>{agent.agent_name}</strong><p>{agent.output_summary}</p></div><span className="status-pill complete">complete</span></div>)}</div></article><article className="card"><SectionTitle title="Similar issues" count={analysis.similar_issues.length} /><div className="similar-list">{analysis.similar_issues.map(issue => <div key={issue.id}><div><strong>{issue.title}</strong><p>{issue.department} · {new Date(issue.created_at).toLocaleDateString()}</p></div><span>{Math.round(issue.confidence * 100)}% match</span></div>)}</div></article></section><section className="card solutions-card"><SectionTitle title="Proven solutions" count={analysis.previous_solutions.length} />{analysis.previous_solutions.map(solution => <div className="solution-row" key={solution.id}><div className="solution-score"><strong>{Math.round(solution.reuse_confidence * 100)}%</strong><span>reuse confidence</span></div><div><h3>{solution.title}</h3><p>{solution.description}</p><span>Owner · {solution.owner}</span></div><button className="primary-button" onClick={() => void implement(solution.id)} disabled={!!implementing}>{implementing === solution.id ? 'Building plan…' : 'Build action plan'}</button></div>)}</section>{plan && <Plan plan={plan} />}</> : <EmptyState title="Analysis unavailable" description="Submit a new observation or retry this request." />}</div>
}
function SectionTitle({ title, count }: { title: string; count: number }) { return <div className="section-title"><h2>{title}</h2><span>{count}</span></div> }
function AnalysisSkeleton() { return <div className="analysis-loading"><Skeleton className="hero-skeleton"/><div><Skeleton/><Skeleton/></div><Skeleton className="wide-skeleton"/></div> }
function Plan({ plan }: { plan: ImplementResponse }) { return <section className="card plan-card"><p className="eyebrow">Recommended implementation plan</p><h2>Turn insight into action</h2><p>{plan.implementation_plan}</p><div className="timeline">{plan.actions.map(action => <div key={action.step}><span>{action.step}</span><div><strong>{action.description}</strong><p>{action.owner}</p></div><em>Day {action.due_days}</em></div>)}</div><div className="stakeholders"><strong>Stakeholders</strong>{plan.stakeholders.map(item => <span key={item}>{item}</span>)}</div></section> }
